config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :activities do
    resources :slots, only: [:new, :create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :kids do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:destroy]
  get "book_activity/:kid_id", to: 'pages#book_activity', as: :book_activity
  get "book_slot/:activity_id/:kid_id", to: 'pages#book_slot', as: :book_slot
  get "dashboard", to: 'pages#dashboard', as: :dashboard
  get "slot_bookings/:slot_id", to: 'pages#slot_bookings', as: :slot_bookings
  get "notify", to: 'allerts#notify', as: :notify
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user
  has_many :slots, dependent: :destroy
  has_one_attached :photo
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :kid
  belongs_to :slot
end

app/models/kid.rb
class Kid < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  validates :first_name, presence: true
  validates :age, presence: true
  validates :gender, presence: true
end

app/models/slot.rb
class Slot < ApplicationRecord
  belongs_to :activity
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def index
    # @activities = Activity.all
    if params[:query].present?
      sql_query = "name ILIKE :query OR description ILIKE :query"
      @activities = Activity.where(sql_query, query: "%#{params[:query]}%")
    else
      @activities = Activity.all
    end
    # @markers = @activities.geocoded.map do |activity|
    #   {
    #     lat: activity.latitude,
    #     lng: activity.longitude
    #   }
    # end
  end

  def new
    @activity = Activity.new
  end

  def show
    @activity = Activity.find(params[:id])
  end

  def create
    @activity = Activity.new(activity_params)
    @activity.user = current_user
    if @activity.save
      redirect_to activity_path(@activity)
    else
      render :new
    end
  end

  def edit
    @activity = Activity.find(params[:id])
  end

  def update
    @activity = Activity.find(params[:id])
    if @activity.update(activity_params)
      redirect_to @activity, notice: 'Activity was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy!
    redirect_to activitys_path
  end

  private

  def activity_params
    params.require(:activity).permit(:name, :description, :price, :location, :availability, :photo)
  end
end

app/controllers/allerts_controller.rb
class AllertsController < ApplicationController
  def notify
    @slot_id = params[:id]
    @booking = Booking.find(params[:booking_id])

    @booking.update(status: true)

    client = Twilio::REST::Client.new(ENV['TWILIO_ACCOUNT_SID'], ENV['TWILIO_AUTH_TOKEN'])
    client.messages.create({
    from: '+13253350403',
    to: '+4915259020002',
    body: 'Dear parent, your kid arrived on time at our club today. Have a calm day.'
    })

    redirect_to slot_bookings_path(slot_id: @slot_id)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @kid = Kid.find(params[:kid_id])
    @booking = Booking.new
  end

  #if there is a booking for kid_id with the slot_id then the kid cannot book again

  def create
    @booking = Booking.new
    @kid = Kid.find(params[:kid_id])
    @slot = Slot.find(params[:slot_id])
    @already_booked = Booking.where(slot: @slot, kid: @kid).exists?
    unless @already_booked
      @booking.slot = @slot
      @booking.kid = @kid
      @booking.save
    end
    redirect_to kid_path(@kid)
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy!
    redirect_to kid_path(@booking.kid)
  end
end

app/controllers/kids_controller.rb
class KidsController < ApplicationController
  def index
    @kids = Kid.all
  end

  def new
    @kid = Kid.new
  end

  def show
    @kid = Kid.find(params[:id])
    @bookings = Booking.where(kid_id: @kid.id)
  end

  def create
    @kid = Kid.new(kid_params)
    @kid.user = current_user
    if @kid.save
      redirect_to kid_path(@kid)
    else
      render :new
    end
  end

  def edit
    @kid = Kid.find(params[:id])
  end

  def update
    @kid = Kid.find(params[:id])
    if @kid.update(kid_params)
      redirect_to @kid, notice: 'kid profile successfully edited'
    else
      render :edit
    end
  end

  def destroy
    @kid = Kid.find(params[:id])
    @kid.destroy!
    redirect_to kids_path
  end

  private

  def kid_params
    params.require(:kid).permit(:first_name, :last_name, :age, :gender)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end

  def book_activity
    @kid = Kid.find(params[:kid_id])
    if params[:query].present?
      sql_query = "name ILIKE :query OR description ILIKE :query"
      @activities = Activity.where(sql_query, query: "%#{params[:query]}%")
    else
      @activities = Activity.all
    end
  end

  def book_slot
    @activity = Activity.find(params[:activity_id])
    @kid = Kid.find(params[:kid_id])
  end

  def dashboard
    @bookings = Booking.all
    if params[:query].present?
      sql_query = "name ILIKE :query OR description ILIKE :query"
      @activities = Activity.where(sql_query, query: "%#{params[:query]}%")
    else
      @activities = Activity.all
    end
    @user_activities = @activities.where(user_id: current_user.id)
    @my_activities = current_user.activities
  end

  def slot_bookings
    @activities = Activity.all
    @slots = Slot.all
    @user_activities = @activities.where(user_id: current_user.id)
    @slot = Slot.find(params[:slot_id])
  end

end

app/controllers/slots_controller.rb
class SlotsController < ApplicationController
  def new
    @slot = Slot.new
    @activity = Activity.find(params[:activity_id])
  end

  def create
    @slot = Slot.new(slot_params)
    @activity = Activity.find(params[:activity_id])
    @slot.activity = @activity
    if @slot.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  private

  def slot_params
    params.require(:slot).permit(:time, :date)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
# app/helpers/meta_tags_helper.rb

module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/activities/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-8">
      <%= simple_form_for(@activity) do |f| %>
        <%= f.input :name, :input_html => { :class => 'booking-input' } %>
        <%= f.input :description, :input_html => { :class => 'booking-input' } %>
        <%= f.input :price, :input_html => { :class => 'booking-input' } %>
        <%= f.input :location, :input_html => { :class => 'booking-input' } %>
        <%= f.input :photo, as: :file, label: false, wrapper_html: { class: "text-center" }, input_html: { class: "d-inline" } %>
        <%= f.submit "Submit", class: "btn btn-nav w-100 mr-sm-4" %>
      <% end %>
    </div>
  </div>
</div>

app/views/activities/edit.html.erb
<div class="row justify-content-center my-3">
  <h1>edit your activity</h1>
  <%= render 'form', activity: @activity %>
</div>

app/views/activities/index.html.erb
<div class="d-flex">
  <div class="container">
    <%= link_to root_path, class: "link_to" do %>
      <div class="arrow">
        <%= image_tag "backarrow.png" %>
      </div>
    <% end %>
  </div>

</div>

<div class="d-flex justify-content-center">
  <%= form_tag activities_path, class: "form-search d-flex col-9", method: :get do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Search"
    %>
    <%= submit_tag "Go", class: "btn btn-search mb-0" %>
  <% end %>
</div>

<div class="homepage-container">

  <div class='header'>
    <h1 class=""></h1>
  </div>

  <% @activities.each do |activity| %>
    <%= link_to activity_path(activity), class: "d-block" do %>
      <div class="card-index-activity">
        <% if activity.photo.attached? %>
          <%= cl_image_tag activity.photo.key,crop: :fill, width: 250  %>
        <% end %>
        <h1><%= activity.name %></strong></h1>
        <div class="description-card-activity">
          <p> <%= activity.description.first(49)%>...</p>
        </div>
      </div>
    <% end %>
  <% end %>

</div>

app/views/activities/new.html.erb
<div class="container" >
  <%= link_to root_path, class: "link_to" do %>
    <div class="arrow">
      <%= image_tag "backarrow.png" %>
    </div>
  <% end %>
</div>

<div class="row justify-content-center my-3">
  <h1>add a new activity</h1>
  <%= render 'form', activity: @activity %>
</div>

app/views/activities/show.html.erb
<div class="container" >
  <%= link_to activities_path, class: "link_to" do %>
    <div class="arrow">
      <%= image_tag "backarrow.png" %>
    </div>
  <% end %>
</div>

<div class='show-container'>
    <%#=cl_image_tag @activity.photo.key%>

  <div class='info-text mx-4'>
    <% if @activity.photo.attached? %>
      <%= cl_image_tag @activity.photo.key,crop: :fill %>
    <% end %>
    <div class="mr-3 ml-3 mt-3 ">

      <h1><strong><%= @activity.name %></strong></h1>
      <p><%= @activity.description %></p>

      <div class="icons text-left ml-4 my-4">
      <p><strong>📍</strong><%= @activity.location%></p>
      <div class="mt-4 ">
      <h3><strong class="mr-2">⏰</strong><%= @activity.duration%>min</h3>
      <div class="mt-4 ">
      <h3><strong class="mr-2">🏷</strong><%= @activity.price %>€</h3>
     </div>
    </div>
    </div>
    </div>


  <% if @kids.count == 0 %>
  <p class="mx-3">to book an activity, you need to <%= link_to "add a kid", new_kid_path(), class: "" %></p>
  <% else %>
    <div class="dropdown">
      <button class="btn btn-book-show dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        choose a kid to book
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <% @kids.each do |kid| %>
        <%= link_to kid.first_name, book_slot_path(activity_id: @activity.id, kid_id: kid.id), class: "dropdown-item" %>
        <% end %>
      </div>
    </div>
  <% end %>


  </div>






  </div>

  <div class="text-center">
    <% if current_user == @activity.user %>
      <div class='btn btn-destroy sm-4'><%= link_to "delete activity", activity_path(@activity), method: :delete, data: {confirm: "Are you sure?"}  %></div>
    <% end %>
    </div>

app/views/kids/edit.html.erb
<div class="container" >
  <%= link_to kid_path(@kid), class: "link_to" do %>
    <div class="arrow">
      <%= image_tag "backarrow.png" %>
    </div>
  <% end %>
</div>

<div class="row justify-content-center my-3">
  <%= simple_form_for [ @kid ] do |f| %>
    <%= f.input :first_name%>
    <%= f.input :last_name%>
    <%= f.input :gender, collection: ["female", "male", "neutral", "others"] %>
    <%= f.input :age %>
    <div class="row justify-content-center my-3">
      <%= f.submit "save",id: 'create_kid'%>
    </div>

    <div class='row justify-content-center my-3'><%= link_to "remove kid's profile", kid_path(@kid), method: :delete, data: {confirm: "are you sure that you want to remove this?"}, id: "create_kid"  %></div>
  <% end %>
</div>

app/views/kids/index.html.erb
<div class="container" >
  <%= link_to root_path, class: "link_to" do %>
    <div class="arrow">
      <%= image_tag "backarrow.png" %>
    </div>
  <% end %>
</div>

<div class='cards_kid'>
  <div class="text-center mb-3">
    <h3>select a kid</h3>
  </div>
  <% @kids.each do |kid|%>
      <% if current_user == kid.user %>
        <div class='card_kid'>
          <%= link_to kid_path(kid), class: "d-block" do %>
            <% if kid.gender == 'female' %>
              <%= image_tag "girl1.png" %>
            <% elsif kid.gender == 'male' %>
              <%= image_tag "boy1.png" %>
            <% else %>
              <%= image_tag "bear.png" %>
            <% end %>
            <h4><%= kid.first_name %> <%= kid.last_name %></h4>
            <div class='age'>
              <h4><%= kid.age %> <%= image_tag "cake.png" %></h4>
            </div>
          <% end %>
        </div>
      <% end %>
  <% end %>
</div>
<div class='plus-icon'>
  <%= link_to  new_kid_path() do %>
    <img src="https://cdn-icons-png.flaticon.com/512/1828/1828764.png" alt="plus">
  <% end %>
</div>

app/views/kids/new.html.erb
<div class="container" >
  <%= link_to kids_path, class: "link_to" do %>
    <div class="arrow">
      <%= image_tag "backarrow.png" %>
    </div>
  <% end %>
</div>

<div class="row justify-content-center my-3">
  <%= simple_form_for [ @kid ] do |f| %>
    <%= f.input :first_name%>
    <%= f.input :last_name%>
    <%= f.input :gender, collection: ["female", "male", "neutral", "others"] %>
    <%= f.input :age %>
    <div class="row justify-content-center my-5">
      <%= f.submit "create",id: 'create_kid'%>
    </div>
  <% end %>
</div>

app/views/kids/show.html.erb
<div class="container" >
  <%= link_to kids_path, class: "link_to" do %>
    <div class="arrow">
      <%= image_tag "backarrow.png" %>
    </div>
  <% end %>
</div>

<div class='show_info_cards'>
  <% if @kid.gender == 'female' %>
    <%= image_tag "girl1.png" %>
  <% elsif @kid.gender == 'male' %>
    <%= image_tag "boy1.png" %>
  <% else %>
    <%= image_tag "bear.png" %>
  <% end %>
  <h2><%= @kid.first_name%> <%= @kid.last_name %></h2>
  <div class='age_show'>
    <h2><%= @kid.age %> <%= image_tag "cake.png" %></h2>
  </div>
</div>

<div class='row justify-content-center my-4'>
  <%= link_to "book activity", book_activity_path(@kid), class: "booking-btn" %>
</div>

<div class='row justify-content-center my-4'>
  <%= link_to 'edit', edit_kid_path(@kid)%>
</div>

 <div class="text-center">
  <% @bookings.each do |booking| %>
  <div class="booked_info_card">
    <div>
      <%= image_tag "sport.png" %></h2>
    </div>

    <div class="booked_card_text">
      <h5><%= booking.slot.activity.name %></h5>
      <h6><%= booking.slot.day %></h6>
      <h6><%= booking.slot.time %></h6>
    </div>

    <div class=''>
      <div class="cancel-booking-btn"><%= link_to "cancel", booking_path(booking), method: :delete,data: {confirm: "are you sure that you want to cancel your booking for the activity?"}%></div>
    </div>
  </div>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project4habits</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/book_activity.html.erb
<div class="d-flex">
  <div class="container">
    <%= link_to kid_path(@kid), class: "link_to" do %>
      <div class="arrow">
        <%= image_tag "backarrow.png" %>
      </div>
    <% end %>
  </div>

</div>

<div class="d-flex justify-content-center">
  <%= form_tag book_activity_path, class: "form-search d-flex col-9", method: :get do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Search"
    %>
    <%= submit_tag "Go", class: "btn btn-search mb-0" %>
  <% end %>
</div>


<div class='title-booking'>
  <h2>choose your activity for <%= @kid.first_name %></h2>
</div>


<% @activities.each do |activity| %>
    <div class="main-card-booking">
      <h1><%= activity.name %></h1>
      <p class="card-text"><%= activity.description %></p>
      <div class="icons text-left ml-3 my-2">
      <h6>📍 <%= activity.location %></h6>
      <div class="mt-4 ">
      <h3>⏰ <%= activity.duration %>min</h3>
      <div class="mt-4 ">
      <h3>🏷 <%= activity.price %>€</h3>
      <div class="mt-4 ">
      </div>
      </div>
      </div>
      </div>

      <div class="dropdown">
        <button class="btn btn-book-show dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        open slots
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">


      <% activity.slots.each do |slot| %>
        <% @already_booked = Booking.where(slot: slot, kid: @kid).exists? %>
        <% @time = slot.time %>
        <% @day = slot.day %>
        <% @time_already_used = Slot.joins(:bookings).where("time = '#{@time}' AND day = '#{@day}' AND bookings.kid_id = #{@kid.id}").exists? %>
        <% unless @already_booked || @time_already_used%>



        <%= link_to "#{slot.day} " "#{slot.time}", kid_bookings_path(kid_id: @kid.id, slot_id: slot.id), method: :post, data: {confirm: "Are you sure you want to book this slot?"}, class: "dropdown-item" %>




        <% end %>
      <% end %>

      </div>
      </div>


    </div>
<% end %>

app/views/pages/book_slot.html.erb
<div class="container" >
  <%= link_to activity_path(@activity), class: "link_to" do %>
    <div class="arrow">
      <%= image_tag "backarrow.png" %>
    </div>
  <% end %>
</div>

<div class='title-booking justify-content-center'>
  <h2>you can now book your activity for <%= @kid.first_name %></h2>
</div>
<div class="main-card-booking custom-slot">
      <h1><%= @activity.name %></h1>
      <p class="card-text p-4"><%= @activity.description %></p>
      <div class="icons text-left ml-4 my-4">
      <h6>📍 <%= @activity.location %></h6>
      <div class="mt-4 ">
      <h3>⏰ <%= @activity.duration %>min</h3>
      <div class="mt-4 ">
      <h3>🏷 <%= @activity.price %>€</h3>
      </div>
      </div>
      </div>

      <div class="dropdown">
      <button class="btn btn-book-show dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        open slots
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">

      <% @activity.slots.each do |slot| %>




        <%= link_to "#{slot.day} " "#{slot.time}", kid_bookings_path(kid_id: @kid.id, slot_id: slot.id), method: :post, data: {confirm: "Are you sure you want to book this slot?"}, class: "dropdown-item custom-dropdown-item" %>



      <% end %>

      </div>
      </div>

    </div>

app/views/pages/dashboard.html.erb
<div class="d-flex">
  <div class="container">
    <%= link_to root_path, class: "link_to" do %>
      <div class="arrow">
        <%= image_tag "backarrow.png" %>
      </div>
    <% end %>
  </div>

</div>

<div class="d-flex justify-content-center">
  <%= form_tag dashboard_path, class: "form-search d-flex col-9", method: :get do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Search"
    %>
    <%= submit_tag "Go", class: "btn btn-search mb-0" %>
  <% end %>
</div>

<div class="container my-4 text-center">
  <div class="row">
    <div class="col">
      <h2>overview clubs</h2>
      <% if @user_activities.count > 0 %>
        <% @user_activities.each do |activity| %>
          <% if current_user == activity.user %>
            <div class='container-dashboard'>
              <% if activity.photo.attached? %>
                    <%=cl_image_tag activity.photo.key,crop: :fill%>
              <% end %>
              <div class='info-text mx-4'>

                <h1 class="my-4"><strong><%= activity.name %></strong></h1>

                <% if activity.slots.present?  %>

               

                  <div class="dropdown">
                  <button class="btn btn-show dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  schedule
                  </button>
                  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">


                  <% activity.slots.each do |slot| %>
                    <p class="dropdown-item"><%= slot.day %> <%= slot.time %><% if slot.bookings.count > 0 %> <%= link_to "see bookings", slot_bookings_path(slot) %> <% end %>
                  <% end %></p>
                  </div>
                </div>
                <% end %>
              <br>
                <div class="links-dashboard mb-2">
                  <%= link_to 'add booking time', new_activity_slot_path(activity)%><br>
                  <div class="mt-2 ">
                  <%= link_to 'edit', edit_activity_path(activity) %><br>
                  <div class="mt-2 ">
                  <%= link_to "delete activity", activity_path(activity), method: :delete, data: {confirm: "Are you sure?"}  %>
                </div>
              </div>
              </div>
              </div>
            </div>
          <% end %>
        <% end %>
      <% else %>
        <p>you don't have any activities yet...</p>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<header class="mb-6">
<h1 class="my-4 text-center mt-5">mindful fun for kids</h1>
<h2></h2>
<div class='text-center'>
  <img src="<%= image_path("4habitsnew.png") %>" class="img-fluid" alt="Responsive image">
</div>
</header>


<section>
<div class="container text-center">
<div class="row">

<div class="col-12 mr-3">
<%= link_to "kids", kids_path, class: "btn-home" %>
<div class="col-12 mr-3">
<%= link_to "sports", activities_path, class: "btn-home" %>
</div>
</div>
</div>
</div>
</section>

app/views/pages/slot_bookings.html.erb
<div class="booked-slots m-3 text-center">
<div class="container" >
  <%= link_to dashboard_path, class: "link_to" do %>
    <div class="arrow">
      <%= image_tag "backarrow.png" %>
    </div>
  <% end %>
</div>
<div class="my-2">
<h1><strong><%= @slot.time %></strong></h1>
    <h2><strong><%= @slot.day %></strong></h2>
</div>

<div class='show-container-slots'>
    <%#=cl_image_tag @activity.photo.key%>


  <div class='info-text mx-4'>



    <% @slot.bookings.each do |booking| %>
    <p><strong>Parent:</strong> <%= booking.kid.user.first_name %> <%= booking.kid.user.last_name %></p>
    <p>
    <strong>Kid:</strong> <%= booking.kid.first_name %> <%= booking.kid.last_name %>
    </p>
    <% if !booking.status  %>
      <%= link_to "notify parent", notify_path(id: @slot.id, booking_id: booking.id), class: "btn-home my-2" %>
    <% else %>
      <h1> notified! </h1>
    <% end %>
    <% end %>

  </div>
</div>





</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links text-center">

  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%#= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <%= image_tag "4habitsnew.png", alt: "4habits" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>


        <% if current_user.owner == true %>
        <li class="nav-item active">

          <%= link_to "dashboard", "/dashboard", class: "btn my-2 btn-nav mr-2" %>
        </li>
        <li class="nav-item">
          <%= link_to "add activity", "/activities/new", class: "btn my-2 btn-nav mr-2" %>
        </li>
        <% else %>
        <li class="nav-item active">
          <%= link_to "find activities", "/activities", class: "btn my-2 btn-nav mr-2" %>
        </li>
        <li class="nav-item active">
          <%= link_to "kids overview", "/kids", class: "btn my-2 btn-nav mr-2" %>
        </li>
        <li class="nav-item">
          <%= link_to "you can add your kid here", "/kids/new", class: "btn my-2 btn-nav mr-2" %>
        </li>
        <% end %>
        <li class="nav-item">
          <%#= image_tag "https://res.cloudinary.com/dgarvanzw/image/upload/v1637142348/Sample_User_Icon_r2zlx0.png", class: "avatar dropdown", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="" aria-labelledby="navbarDropdown">
            <%# <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "log out", destroy_user_session_path, method: :delete, class: "btn my-2 btn-nav mr-2" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "login", new_user_session_path, class: "btn my-2 btn-nav mr-2" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/slots/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-8">
    <h1>Add a new booking time</h1>
      <%= simple_form_for [@activity, @slot] do |f| %>
        <%= f.input :time, :input_html => { :class => 'booking-input' } %>
        <%= f.input :day, :input_html => { :class => 'booking-input' } %>
        <%# <%= f.input :photo, as: :file %>
        <%= f.submit "Submit", class: "btn btn-nav w-100 mr-sm-4" %>
      <% end %>
    </div>
  </div>
</div>